[versions]
accompanistPermissions = "0.37.3"
adaptiveAndroid = "1.2.0"
agp = "9.0.1"
composeMaterial = "1.5.6"
coreSplashscreen = "1.2.0"
kotlin = "2.3.10"
kotlinxCoroutinesPlayServices = "1.10.2"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.4"
composeBom = "2026.02.01"
navigationCompose = "2.9.7"
koinBom = "4.1.1"
playServicesWearable = "19.0.0"
serialization = "2.3.10"
serializationJson = "1.10.0"
coroutines = "1.10.2"
workRuntime = "2.11.1"
ktor = "3.4.0"
constraintlayout = "2.2.1"
constraintlayoutCompose = "1.1.1"
coil = "3.4.0"
onetimepassword = "2.4.1"
playServicesBarcode = "16.1.0"
glance = "1.1.1"
tink = "1.20.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-adaptive-android = { module = "androidx.compose.material3.adaptive:adaptive-android", version.ref = "adaptiveAndroid" }

androidx-wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "composeMaterial" }

androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class-android" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }

androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }

io-ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
io-ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
io-ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
io-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }

play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
play-services-barcode = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "playServicesBarcode" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

io-insert-koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBom" }
io-insert-koin-core = { group = "io.insert-koin", name = "koin-core" }
io-insert-koin-compose = { group = "io.insert-koin", name = "koin-compose" }
io-insert-koin-android = { group = "io.insert-koin", name = "koin-android" }
io-insert-koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
io-insert-koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }

org-jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
org-jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

org-jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

io-coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
io-coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
io-coil-coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }

kotlin-onetimepassword = { group = "dev.turingcomplete", name = "kotlin-onetimepassword", version.ref = "onetimepassword" }

androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "glance" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }

tink-android = { group = "com.google.crypto.tink", name = "tink-android", version.ref = "tink" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }