[versions]
accompanistPermissions = "0.37.3"
adaptiveAndroid = "1.2.0"
agp = "9.0.0"
barcodeScanning = "17.3.0"
cameraLifecycle = "1.5.3"
cameraCamera2 = "1.5.3"
composeMaterial = "1.5.6"
coreSplashscreen = "1.2.0"
kotlin = "2.3.0"
kotlinxCoroutinesPlayServices = "1.10.2"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.3"
composeBom = "2026.01.01"
navigationCompose = "2.9.7"
koinBom = "4.1.1"
playServicesWearable = "19.0.0"
serialization = "2.3.10"
serializationJson = "1.10.0"
coroutines = "1.10.2"
workRuntime = "2.11.1"
ktor = "3.4.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-adaptive-android = { module = "androidx.compose.material3.adaptive:adaptive-android", version.ref = "adaptiveAndroid" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycle" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCamera2" }

androidx-wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "composeMaterial" }

androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class-android" }

androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }

barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }

io-ktor-ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
io-ktor-ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
io-ktor-ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
io-ktor-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }

play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServicesWearable" }

androidx-navigation-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

io-insert-koin-koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBom" }
io-insert-koin-koin-core = { group = "io.insert-koin", name = "koin-core" }
io-insert-koin-koin-compose = { group = "io.insert-koin", name = "koin-compose" }
io-insert-koin-koin-android = { group = "io.insert-koin", name = "koin-android" }
io-insert-koin-koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }
io-insert-koin-koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }

org-jetbrains-kotlinx-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
org-jetbrains-kotlinx-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

org-jetbrains-kotlinx-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }